/** Packaging inventory, never a runtime allowlist. Nguyen's reported historical
 * successes do not enable a connector, routine, webhook or external action.
 * adapter "paid_shadow_contract" = unc.paid-ads-shadow.v1 (src/lib/n8n/paidShadowContract.ts):
 * code-ready, still needs Nguyen's wrapper, a reviewed pinned spec, the paid ledger migration and pinned receivers. */
export const SHADOW_LANE_HANDOFF = [
  { area: "meta", capability: "daily_decisioning", routineId: "D02-W01", adapter: "paid_shadow_contract", requiredEvidence: ["adset_id", "reporting_window", "account_currency", "spend", "purchases", "purchase_value", "product_price_binding", "policy_inputs"], boundary: "CPA ceiling is 50% of the promoted product price, same currency. This is not a separate scaling target or authorization to change budgets." },
  { area: "meta", capability: "creative_testing", routineId: "D02-W02", adapter: "paid_shadow_contract", requiredEvidence: ["ad_ids", "creative_ids", "test_ready_source", "window", "approved_test_budget_or_missing"], boundary: "A conceptual test plan is not three approved test-ready creatives or permission to create even paused ads." },
  { area: "meta", capability: "hook_rotation", routineId: "D02-W03", adapter: "paid_shadow_contract", requiredEvidence: ["ad_id", "frequency", "ctr_windows", "variant_ad_id_or_missing"], boundary: "An unbound proposed hook is a content request, not an executable ad rotation." },
  { area: "meta", capability: "ad_fatigue", routineId: "D02-W04", adapter: "paid_shadow_contract", requiredEvidence: ["ad_id", "window", "frequency", "spend", "purchases", "certified_cpa_policy", "trend_baseline_or_missing"], boundary: "No invented fatigue trend, target CPA, purchase count or recommendation presented as a pause." },
  { area: "meta", capability: "creative_test_planner", routineId: "D02-W06", adapter: "paid_shadow_contract", requiredEvidence: ["creative_observations", "measured_vs_hypothesized"], boundary: "Hypotheses remain hypotheses; no measured lift claim or mutation." },
  { area: "meta", capability: "budget_pacing", routineId: "D02-W07", adapter: "paid_shadow_contract", requiredEvidence: ["account_or_adset_grain", "account_timezone", "window_start", "as_of", "currency", "spend", "budget_source", "daily_vs_lifetime"], boundary: "Pacing requires a real budget/window. Unknown budget is not zero, and Meta evidence cannot be labelled Google Ads evidence." },
  { area: "seo", capability: "keyword_opportunity", routineId: "D03-W01", adapter: "existing_keyword_contract", requiredEvidence: ["provider_task", "seed", "country", "language", "domain"], boundary: "Existing unc.keyword-shadow.v1 only; golf travel bag separately US/NZ/AU; first live Unc run still pending." },
  { area: "seo", capability: "content_gap", routineId: "D03-W02", adapter: "produce_step_review", requiredEvidence: ["own_domain", "competitor_domains", "provider_queries", "observed_pages_or_keywords", "recommendation_basis"], boundary: "Separate an observed keyword gap from a crawled page/content claim. Page evidence is required to claim what a page contains." },
  { area: "seo", capability: "serp_position_watch", routineId: "D03-W05", adapter: "source_semantics_change_required", requiredEvidence: ["query", "country", "language", "device", "search_engine", "observed_url", "observed_position", "fetched_at", "matched_prior_observation_or_missing"], boundary: "Current Unc D03-W05 requires Search Console average position/clicks. DataForSEO SERP snapshots are a different source and statistic; no GSC clicks, impressions or delta without matching observations. Codex must adapt before calling this routine integrated." },
  { area: "seo", capability: "competitor_backlink_gap", routineId: "D03-W07", adapter: "reserved_not_executable", requiredEvidence: ["own_domain", "competitor_domains", "referring_domains", "provider_task", "fetched_at"], boundary: "Reserved new ID. Never reuse D03-W06 (competitor page/content analysis). No catalog/endpoint/allowlist exists yet." },
  { area: "content", capability: "viral_hooks", routineId: "D01-W02", adapter: "source_semantics_change_required", requiredEvidence: ["search_query", "source_urls", "fetched_at", "observed_vs_hypothesis"], boundary: "Search-derived hooks are hypotheses; do not claim TikTok/Instagram views or viral performance without those native observations." },
  { area: "content", capability: "customer_questions", routineId: "D01-W03", adapter: "source_semantics_change_required", requiredEvidence: ["search_query", "source_urls", "fetched_at", "question_source_type"], boundary: "Search questions are market-research questions, not first-party customer tickets/reviews or measured frequency." },
  { area: "email", capability: "welcome", routineId: "D05-W01", adapter: "n8n_owned_decision", reportedExecution: "63", requiredEvidence: ["klaviyo_account", "flow_id", "message_id", "current_copy", "metric_window_or_missing"], boundary: "Return inspectable replacement copy. Campaign statistics are not automatically welcome-flow message performance." },
  { area: "email", capability: "segmentation", routineId: "D05-W03", adapter: "source_semantics_change_required", reportedExecution: "69", requiredEvidence: ["klaviyo_account", "segment_id_or_new_definition", "definition", "population_source", "measured_size_or_missing"], boundary: "Current Unc prechecks require Shopify customer data; Klaviyo evidence cannot silently be relabelled Shopify rows. Definitions are proposals, not created segments." },
  { area: "email", capability: "post_purchase", routineId: "D05-W05", adapter: "n8n_owned_decision", reportedExecution: "70", requiredEvidence: ["klaviyo_account", "flow_id", "product_context", "delivery_timing_source_or_missing", "current_message_or_missing"], boundary: "Draft copy only. Do not claim delivery timing, ticket counts or order history from an unrelated campaign read." },
  { area: "email", capability: "review_timing", routineId: "D05-W06", adapter: "n8n_owned_decision", reportedExecution: "71", requiredEvidence: ["klaviyo_account", "flow_id", "current_delay", "proposed_delay", "delivery_or_review_source_or_missing", "suppression_source_or_missing"], boundary: "A proposed delay is not measured peak review time. Missing delivery/review/suppression evidence remains visible." },
  { area: "email", capability: "campaign_calendar", routineId: "D05-W07", adapter: "produce_step_review", reportedExecution: "62", requiredEvidence: ["klaviyo_account", "campaign_window", "business_context", "approved_events_or_missing"], boundary: "Six-week draft calendar, not scheduled campaigns. Klaviyo attribution is not Shopify-reconciled revenue." },
  { area: "google_ads", capability: "bofu_campaign_plan", routineId: "D02-W09", adapter: "paid_shadow_contract", requiredEvidence: ["google_ads_customer_id", "keyword_query", "country", "language", "network", "currency", "historical_metrics_window", "proposed_groups_and_negatives"], boundary: "Catalog routine D02-W09 (draft-only, PAUSED plans). Served through unc.paid-ads-shadow.v1 lane google_ads; a plan is never a created or activated campaign. No registration, allowance or receiver secret exists yet." },
] as const;

export const SHADOW_LANE_BLOCKED_INPUTS = [
  { routineId: "D02-W05", needs: ["approved_creator_handles", "creator_rights"] },
  { routineId: "D02-W08", needs: ["approved_organic_performance_source"] },
  { routineId: "D03-W03", needs: ["intended_ai_search_probe_source"] },
  { routineId: "D03-W04", needs: ["separately_reopened_cms_admin_authorization"] },
  { routineId: "D05-W02", needs: ["contact_frequency_cap"] },
  { routineId: "D05-W04", needs: ["margin_floor"] },
] as const;
