import {describe,it,expect,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {receiveReviewOutput,reviewIntakeToken,issueReviewIntakeGrant,readReviewIntakeGrant,type ReviewIntakeGrant} from '../reviewIntake';
import type {DbClient,Row} from '../../db/types';
const id='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
const secret='test-secret-'.repeat(4),now=Date.parse('2026-09-09T00:00:00Z');
const grant:ReviewIntakeGrant={id,workerId:'Junction TEST',contextGeneration:0,sourceRunId:id,
 output:{ref:{accountId:id,artifactId:id,outputId:id,revision:0},kind:'brief',sectionIds:[],durationSeconds:null},
 issuedAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+60000).toISOString()};
const content={title:'Finished draft',body:'Internal test. Nothing sent.'};
function setup(g=grant){return {enabled:true,secret,resolve:vi.fn().mockResolvedValue(g),released:vi.fn().mockReturnValue(true),checkContext:vi.fn().mockResolvedValue(undefined),
 storage:{isPrivate:vi.fn().mockResolvedValue(true),read:vi.fn()},register:vi.fn().mockResolvedValue({outputId:id,revision:0,duplicate:false,reviewUrl:`/app/review/${id}?account=${id}`}),now:()=>now};}
function request(value:unknown={content},g=grant,auth=`Bearer ${reviewIntakeToken(g,secret)}`){return new Request('https://junction.test/callback',{method:'POST',headers:{authorization:auth,'content-type':'application/json'},body:JSON.stringify(value)});}
function grantStore(){const rows:Row[]=[];const db={from:()=>({insert:async(row:Row)=>{
 if(rows.some(r=>r.id===row.id))return {error:{code:'23505'},data:null};rows.push(row);return {error:null,data:null};
},select:()=>{const filters:[string,unknown][]=[];const q={eq:(k:string,v:unknown)=>{filters.push([k,v]);return q;},maybeSingle:async()=>({error:null,data:rows.find(r=>filters.every(([k,v])=>r[k]===v))??null})};return q;}})} as unknown as DbClient;return {rows,db};}
describe('persisted intake grants (simulated database)',()=>{
 it('persists exact scope but never the signing secret or derived token',async()=>{const f=grantStore();const issued=await issueReviewIntakeGrant(f.db,grant,secret,now);expect(await readReviewIntakeGrant(f.db,id)).toEqual(grant);expect(issued.authorization).toBe(`Bearer ${reviewIntakeToken(grant,secret)}`);expect(JSON.stringify(f.rows)).not.toContain(secret);expect(JSON.stringify(f.rows)).not.toContain(issued.authorization);});
 it('reissues the same callback without duplicate grants',async()=>{const f=grantStore();const first=await issueReviewIntakeGrant(f.db,grant,secret,now);expect(await issueReviewIntakeGrant(f.db,grant,secret,now)).toEqual(first);expect(f.rows).toHaveLength(1);});
 it('refuses conflicting ID without replacing original scope',async()=>{const f=grantStore();await issueReviewIntakeGrant(f.db,grant,secret,now);await expect(issueReviewIntakeGrant(f.db,{...grant,workerId:'other'},secret,now)).rejects.toThrow('Conflicting');expect(await readReviewIntakeGrant(f.db,id)).toEqual(grant);});
 it('does not issue expired scope or short signing keys',async()=>{const f=grantStore();await expect(issueReviewIntakeGrant(f.db,grant,secret,now+60000)).rejects.toThrow();await expect(issueReviewIntakeGrant(f.db,grant,'short',now)).rejects.toThrow();expect(f.rows).toHaveLength(0);});
 it('refuses row/account corruption',async()=>{const f=grantStore();await issueReviewIntakeGrant(f.db,grant,secret,now);f.rows[0].account_id=other;expect(await readReviewIntakeGrant(f.db,id)).toBeNull();});
});
describe('external finished-output intake (simulated storage; no Grok proof)',()=>{
 it('registers only the stored scope and returns no execution authority',async()=>{const d=setup();const r=await receiveReviewOutput(request(),id,d);expect(r.status).toBe(201);expect(await r.json()).toMatchObject({saved:true,executed:false,outputId:id});expect(d.register).toHaveBeenCalledWith(grant,content);expect(d.checkContext).toHaveBeenCalledTimes(2);expect(d.storage.read).not.toHaveBeenCalled();});
 it('disabled or missing auth does not access the database',async()=>{for(const disabled of [true,false]){const d=setup();d.enabled=!disabled;const r=await receiveReviewOutput(request(undefined,grant,''),id,d);expect(r.status).toBe(disabled?503:401);expect(d.resolve).not.toHaveBeenCalled();}});
 it('rejects wrong token and changed account scope',async()=>{for(const g of [grant,{...grant,output:{...grant.output,ref:{...grant.output.ref,accountId:other}}}]){const d=setup(g);const r=await receiveReviewOutput(request(undefined,grant,g===grant?`Bearer ${'a'.repeat(43)}`:undefined),id,d);expect(r.status).toBe(401);expect(d.register).not.toHaveBeenCalled();}});
 it('rejects mismatched grant ID',async()=>{const d=setup({...grant,id:other});expect((await receiveReviewOutput(request(),id,d)).status).toBe(401);});
 it('rejects expired, future and excessive lifetime',async()=>{for(const g of [{...grant,expiresAt:new Date(now).toISOString()},{...grant,issuedAt:new Date(now+1).toISOString()},{...grant,expiresAt:new Date(now+3600000).toISOString()}]){const d=setup(g);expect((await receiveReviewOutput(request({content},g),id,d)).status).toBe(410);expect(d.register).not.toHaveBeenCalled();}});
 it('requires exact account release',async()=>{const d=setup();d.released.mockReturnValue(false);expect((await receiveReviewOutput(request(),id,d)).status).toBe(503);expect(d.checkContext).not.toHaveBeenCalled();});
 it('refuses context changes without registration',async()=>{const d=setup();d.checkContext.mockRejectedValue(new Error('changed'));expect((await receiveReviewOutput(request(),id,d)).status).toBe(503);expect(d.register).not.toHaveBeenCalled();});
 it('rejects attempts to submit scope/action/URL fields',async()=>{for(const value of [{content,accountId:other},{content,action:'publish'},{content:{...content,imagePath:'https://untrusted.test/x'}}]){const d=setup();expect((await receiveReviewOutput(request(value),id,d)).status).toBe(400);expect(d.register).not.toHaveBeenCalled();}});
 it('bounds JSON bytes before registration',async()=>{const d=setup();expect((await receiveReviewOutput(request({content:{title:'x',body:'x'.repeat(130000)}}),id,d)).status).toBe(400);expect(d.register).not.toHaveBeenCalled();});
 it('requires finished media for image/email/video',async()=>{for(const kind of ['image','email','video'] as const){const g={...grant,output:{...grant.output,kind,durationSeconds:kind==='video'?10:null}};const d=setup(g);expect((await receiveReviewOutput(request({content},g),id,d)).status).toBe(400);}});
 it('verifies media bytes and derives storage key, never an external URL',async()=>{const bytes=new Uint8Array([1,2,3]);const media={image:{format:'png',bytes:3,sha256:createHash('sha256').update(bytes).digest('hex')}};const g={...grant,output:{...grant.output,kind:'image' as const}};const d=setup(g);d.storage.read.mockResolvedValue(bytes);expect((await receiveReviewOutput(request({content:{title:'Graphic',media}},g),id,d)).status).toBe(201);expect(d.storage.read).toHaveBeenCalledWith(`${id}/0/${id}/0/image.png`,3);});
 it('refuses missing, wrong size or wrong hash media',async()=>{for(const bytes of [null,new Uint8Array([1]),new Uint8Array([1,2,3])]){const d=setup();d.storage.read.mockResolvedValue(bytes);expect((await receiveReviewOutput(request({content:{...content,media:{image:{format:'png',bytes:3,sha256:'a'.repeat(64)}}}}),id,d)).status).toBe(409);expect(d.register).not.toHaveBeenCalled();}});
 it('refuses public bucket without downloading',async()=>{const d=setup();d.storage.isPrivate.mockResolvedValue(false);expect((await receiveReviewOutput(request({content:{...content,media:{image:{format:'png',bytes:3,sha256:'a'.repeat(64)}}}}),id,d)).status).toBe(503);expect(d.storage.read).not.toHaveBeenCalled();});
 it('rechecks expiry after media work',async()=>{const d=setup();let calls=0;d.now=()=>calls++===0?now:now+60000;expect((await receiveReviewOutput(request(),id,d)).status).toBe(410);expect(d.register).not.toHaveBeenCalled();});
 it('returns a duplicate receipt without generating anything',async()=>{const d=setup();d.register.mockResolvedValue({outputId:id,revision:0,duplicate:true,reviewUrl:'/app/review/x'});const r=await receiveReviewOutput(request(),id,d);expect(r.status).toBe(200);expect(await r.json()).toMatchObject({duplicate:true,executed:false});});
 it('does not claim completion on uncertain storage',async()=>{const d=setup();d.register.mockRejectedValue(new Error('timeout'));const r=await receiveReviewOutput(request(),id,d);expect(r.status).toBe(503);expect(await r.json()).not.toHaveProperty('saved');});
});
