-- Synthetic accounts/runs only, real PostgreSQL role/trigger semantics. Always rollback.
begin;
set local lock_timeout='5s';
set local statement_timeout='20s';
set local role service_role;
do $$
declare
 a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); r uuid; r2 uuid; art uuid; ap uuid;
 denied boolean;
begin
 insert into public.accounts(id,name) values(a,'UNC_RUN_CONTEXT_CANARY'),(b,'UNC_RUN_CONTEXT_CANARY_OTHER');
 insert into public.routine_runs(account_id,routine_id,version,mode,status) values(a,'D01-W01',1,'dry_run','running') returning id into r;
 insert into public.artifacts(account_id,run_id,routine_id,kind,title,body) values(a,r,'D01-W01','post_set','old','old') returning id into art;
 insert into public.approvals(account_id,run_id,routine_id,title,status) values(a,r,'D01-W01','old','pending') returning id into ap;
 insert into public.receipts(account_id,run_id,kind,description) values(a,r,'draft','old');
 update public.accounts set context_generation=1 where id=a;

 denied:=false;
 begin insert into public.routine_runs(account_id,routine_id,version) values(a,'D01-W01',1);
 exception when serialization_failure then denied:=true; end;
 assert denied,'legacy new-run admission survived reset';
 denied:=false;
 begin update public.routine_runs set summary='late finish' where id=r;
 exception when serialization_failure then denied:=true; end;
 assert denied,'old run updated after reset';
 denied:=false;
 begin update public.routine_runs set context_generation=1 where id=r;
 exception when check_violation then denied:=true; end;
 assert denied,'old run relabelled';
 denied:=false;
 begin insert into public.artifacts(account_id,run_id,routine_id,kind,title,body) values(a,r,'D01-W01','post_set','late','late');
 exception when serialization_failure then denied:=true; end;
 assert denied,'old run artifact accepted';
 denied:=false;
 begin update public.artifacts set body='late' where id=art;
 exception when serialization_failure then denied:=true; end;
 assert denied,'old artifact edited';
 denied:=false;
 begin update public.approvals set status='approved' where id=ap;
 exception when serialization_failure then denied:=true; end;
 assert denied,'old approval accepted';
 denied:=false;
 begin insert into public.receipts(account_id,run_id,kind,description) values(a,r,'notification','late success');
 exception when serialization_failure then denied:=true; end;
 assert denied,'old receipt accepted';
 denied:=false;
 begin insert into public.artifacts(account_id,routine_id,kind,title,body) values(a,'D01-W01','post_set','missing parent','late');
 exception when serialization_failure then denied:=true; end;
 assert denied,'null parent bypassed captured identity';

 insert into public.routine_runs(account_id,routine_id,version,mode,status,context_generation)
   values(a,'D01-W01',1,'dry_run','running',1) returning id into r2;
 insert into public.artifacts(account_id,run_id,routine_id,kind,title,body) values(a,r2,'D01-W01','post_set','current','current');
 insert into public.approvals(account_id,run_id,routine_id,title,status) values(a,r2,'D01-W01','current','pending');
 insert into public.receipts(account_id,run_id,kind,description) values(a,r2,'draft','current');
 update public.routine_runs set snapshot=jsonb_build_object('ctx',jsonb_build_object('account',jsonb_build_object('accountId',a,'contextGeneration',1))) where id=r2;
 denied:=false;
 begin update public.routine_runs set snapshot=jsonb_build_object('ctx',jsonb_build_object('account',jsonb_build_object('accountId',a,'contextGeneration',0))) where id=r2;
 exception when check_violation then denied:=true; end;
 assert denied,'snapshot changed generation';
 denied:=false;
 begin insert into public.artifacts(account_id,run_id,routine_id,kind,title,body) values(b,r2,'D01-W01','post_set','cross tenant','bad');
 exception when check_violation then denied:=true; end;
 assert denied,'cross-tenant parent accepted';
 denied:=false;
 begin insert into public.artifacts(account_id,run_id,routine_id,kind,title,body) values(a,r2,'D01-W02','post_set','wrong routine','bad');
 exception when check_violation then denied:=true; end;
 assert denied,'cross-routine artifact accepted';
 denied:=false;
 begin update public.artifacts set run_id=r2 where id=art;
 exception when check_violation then denied:=true; end;
 assert denied,'old artifact moved to current parent';
 update public.accounts set automation_paused=true where id=a;
 denied:=false;
 begin insert into public.receipts(account_id,run_id,kind,description) values(a,r2,'draft','paused');
 exception when object_not_in_prerequisite_state then denied:=true; end;
 assert denied,'paused receipt accepted';
 update public.accounts set automation_paused=false where id=a;
 denied:=false;
 begin insert into public.receipts(account_id,run_id,kind,description) values(a,r,'draft','after unpause');
 exception when serialization_failure then denied:=true; end;
 assert denied,'unpause revived an old generation';
 insert into public.routine_runs(account_id,routine_id,version,mode,status) values(b,'D01-W01',1,'dry_run','running');
 assert (select body='old' from public.artifacts where id=art),'history was changed';
 assert (select count(*)=2 from public.receipts where account_id=a),'rejected writes left rows';
 assert not (select has_function_privilege('anon',p.oid,'EXECUTE') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='unc_private' and p.proname='guard_runtime_run_context');
 assert not (select has_function_privilege('authenticated',p.oid,'EXECUTE') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='unc_private' and p.proname='guard_runtime_run_context');
 assert not has_column_privilege('authenticated','public.routine_runs','context_generation','INSERT');
 assert not has_column_privilege('authenticated','public.routine_runs','context_generation','UPDATE');
 assert not has_column_privilege('anon','public.routine_runs','context_generation','UPDATE');
end $$;
rollback;
select 'PASS: captured runs and linked output reject reset/pause/reparent/tenant/snapshot violations; current and unrelated writes work; all canary rows rolled back' as result;
