-- Rollback only, after all six staged channel/artifact migrations. No provider calls.
set local role service_role;
do $$
declare acct uuid:=gen_random_uuid(); actor uuid; runid uuid:=gen_random_uuid(); fid uuid:=gen_random_uuid();
  lid uuid:=gen_random_uuid(); request jsonb; repeated jsonb; result jsonb; oid uuid; old_oid uuid; attempt uuid:=gen_random_uuid(); denied boolean;
begin
  select user_id into actor from public.account_members where account_id='aa5cfc84-2569-4c99-9b40-67003ae55eda' and role='owner' limit 1;
  assert actor is not null;
  insert into public.accounts(id,name) values(acct,'UNC_ARTIFACT_DELIVERY_CANARY');
  insert into public.account_members(account_id,user_id,role) values(acct,actor,'owner');
  insert into public.routine_runs(id,account_id,routine_id,version,mode,status) values(runid,acct,'D03-W01',1,'dry_run','done');
  insert into public.artifacts(id,account_id,run_id,routine_id,kind,title,body) values(fid,acct,runid,'D03-W01','keyword_list','Golf travel bag','Discovery seed');
  insert into public.channel_links(id,account_id,user_id,channel,external_id,verified_at,meta)
    values(lid,acct,actor,'slack','artifact-canary-'||acct,clock_timestamp(),'{"team_id":"canary-team"}');
  assert (select count(*)=1 from public.list_context_artifacts(acct,0,null,null,null,1));
  assert (select count(*)=0 from public.list_context_artifacts(acct,1,null,null,null,1));
  request:=public.prepare_artifact_delivery(acct,0,actor,fid,0,'slack','Original copy');
  oid:=(request->'operations'->0->>'id')::uuid; old_oid:=oid;
  assert oid is not null;
  repeated:=public.prepare_artifact_delivery(acct,0,actor,fid,0,'slack','Retry cannot change content');
  assert repeated->>'id'=request->>'id' and repeated->'operations'->0->>'body'='Original copy','retry rebased payload';
  update public.channel_links set external_id='replacement-'||acct where id=lid;
  repeated:=public.prepare_artifact_delivery(acct,0,actor,fid,0,'slack','Retry after rebind');
  assert repeated->>'id'=request->>'id','rebind created another request';
  result:=public.claim_channel_outbound(oid,attempt);
  assert result->>'claimed'='false' and result->'row'->>'status'='cancelled','old destination was rebased';
  result:=public.decide_context_artifact(acct,0,actor,fid,0,'edit',null,'New draft');
  assert result->'artifact'->>'revision'='1' and result->'artifact'->>'edited_body'='New draft';
  assert (select count(*)=1 from public.taste_events where account_id=acct);
  assert (select count(*)=1 from public.receipts where account_id=acct);
  denied:=false;
  begin perform public.decide_context_artifact(acct,0,actor,fid,0,'edit',null,'Stale edit');
  exception when serialization_failure then denied:=true; end;
  assert denied,'same-status stale edit accepted';
  assert (select count(*)=1 from public.receipts where account_id=acct),'failed edit left receipt';
  request:=public.prepare_artifact_delivery(acct,0,actor,fid,1,'slack','New draft');
  oid:=(request->'operations'->0->>'id')::uuid;
  assert oid<>old_oid;
  perform public.decide_context_artifact(acct,0,actor,fid,1,'hold','Pause this',null);
  result:=public.claim_channel_outbound(oid,gen_random_uuid());
  assert result->>'claimed'='false' and result->'row'->>'status'='cancelled','held draft drained';
  perform public.decide_context_artifact(acct,0,actor,fid,2,'edit',null,'Last draft');
  request:=public.prepare_artifact_delivery(acct,0,actor,fid,3,'slack','Last draft');
  oid:=(request->'operations'->0->>'id')::uuid;
  update public.account_members set role='member' where account_id=acct and user_id=actor;
  result:=public.claim_channel_outbound(oid,gen_random_uuid());
  assert result->>'claimed'='false','demoted owner could send';
  denied:=false;
  begin perform public.decide_context_artifact(acct,0,actor,fid,3,'approve');
  exception when insufficient_privilege then denied:=true; end;
  assert denied,'member decision accepted';
  update public.account_members set role='owner' where account_id=acct and user_id=actor;
  perform public.decide_context_artifact(acct,0,actor,fid,3,'edit',null,'Accepted before reset');
  request:=public.prepare_artifact_delivery(acct,0,actor,fid,4,'slack','Accepted before reset');
  oid:=(request->'operations'->0->>'id')::uuid; attempt:=gen_random_uuid();
  result:=public.claim_channel_outbound(oid,attempt);
  assert result->>'claimed'='true';
  assert public.claim_channel_outbound(oid,gen_random_uuid())->>'claimed'='false','duplicate send claim';
  update public.accounts set context_generation=1,automation_paused=true where id=acct;
  perform public.finish_channel_outbound(oid,attempt,'sent','synthetic-acceptance');
  delete from public.channel_links where id=lid;
  assert (select count(*)=4 from public.artifact_deliveries where account_id=acct),'original deliveries lost';
  assert (select captured_link_id=lid and link_id is null and status='sent' from public.outbound_messages where id=oid);
  assert public.project_channel_outbound(oid) is null,'old copy projected into new context';
  assert (select count(*)=0 from public.list_context_artifacts(acct,1,null,null,null,1));
  denied:=false;
  begin perform public.decide_context_artifact(acct,0,actor,fid,4,'approve'); exception when serialization_failure then denied:=true; end;
  assert denied,'archived decision accepted';
  assert not has_table_privilege('authenticated','public.artifact_deliveries','SELECT');
  assert not has_column_privilege('authenticated','public.artifacts','edited_body','UPDATE');
end $$;
reset role;
set local role authenticated;
do $$ declare denied boolean:=false; begin
  begin perform public.prepare_artifact_delivery(gen_random_uuid(),0,gen_random_uuid(),gen_random_uuid(),0,'slack','No');
  exception when insufficient_privilege then denied:=true; end;
  assert denied,'client send RPC exposed';
end $$;
reset role;
select 'PASS: atomic decision/receipt; revision CAS; captured delivery set; duplicate/rebind/held/owner/reset denial; original acceptance retained; real client RPC denial' as artifact_canary;
