-- Unc beta seed — generated by scripts/seed-beta.ts --sql (2026-09-02T09:00:00.000Z). Do not edit by hand; re-generate.
-- Apply with the service role (Supabase SQL editor, or POST /v1/projects/<ref>/database/query) AFTER
-- migrations 0001–0009. Idempotent: accounts keyed on exact name; goals / resource_profiles /
-- business_profiles / team_members / account_state_meta are upserted (the seed wins — re-applying
-- after a founder edited them overwrites the edit, same as re-running the seeder); connectors,
-- chat_messages and plans are insert-only (never reset a live connection, a real thread or an
-- agreed plan). Membership is NOT written: the beta_invites inserts at the end of each block are
-- commented out with an [EMAIL: …] placeholder — fill the founder's address, uncomment, apply.
-- Accounts: unity-mma → "Unity MMA" · dbh → "Deep Blue Health" · avgar → "AVGAR Sport" · home-invasion → "Home Invasion" · rory → "Rory O'Keefe" · aerspan → "Aerspan Airdomes"

-- ===== unity-mma → Unity MMA =====
insert into accounts (name, currency) select 'Unity MMA', 'NZD' where not exists (select 1 from accounts where name = 'Unity MMA');
update accounts set currency = 'NZD' where name = 'Unity MMA';
insert into goals (account_id, category, tier, title, baseline, baseline_date, deadline)
  values ((select id from accounts where name = 'Unity MMA'), 'leads', 'governing', '30 new membership sign-ups/mo', null, null, '2027-03-01'::date)
  on conflict (account_id, category) do update set tier = excluded.tier, title = excluded.title, baseline = excluded.baseline, baseline_date = excluded.baseline_date, deadline = excluded.deadline, updated_at = now();
insert into resource_profiles (account_id, budget_monthly, hours_weekly, reinvestment, gross_margin_pct, website, socials, skills, known_platforms, postures, breadth)
  values ((select id from accounts where name = 'Unity MMA'), 0, 0, 'balanced', null, null, '["instagram.com/unitymma_"]'::jsonb, array['Video', 'Community']::text[], array['Instagram', 'TikTok']::text[], array['brand_led']::text[], 'focused')
  on conflict (account_id) do update set budget_monthly = excluded.budget_monthly, hours_weekly = excluded.hours_weekly, reinvestment = excluded.reinvestment, gross_margin_pct = excluded.gross_margin_pct, website = excluded.website, socials = excluded.socials, skills = excluded.skills, known_platforms = excluded.known_platforms, postures = excluded.postures, breadth = excluded.breadth, updated_at = now();
insert into team_members (account_id, position, name, role, approves)
  values ((select id from accounts where name = 'Unity MMA'), 0, 'You', 'Founder', 'Content, Paid ads, SEO, Sales, Email & SMS')
  on conflict (account_id, position) do update set name = excluded.name, role = excluded.role, approves = excluded.approves;
insert into plans (account_id, title, phases, narrative)
  select (select id from accounts where name = 'Unity MMA'), 'Brand-led organic', '[{"n":"1","name":"Organic brand engine","status":"ACTIVE","routines":["Founder content engine","Social repurposing","Customer-question mining"],"from_you":"~2 h/wk — your voice and taste, the part only you can do."},{"n":"2","name":"Retention & lifecycle","status":"NOW","routines":["Winback campaign prep","Welcome flow tuning","Review request timing"],"from_you":"~20 min/day clearing approvals."},{"n":"3","name":"Paid amplification","status":"GATED · repeat ≥ 18%","routines":["Daily paid decisioning","Organic-to-paid promotion"],"from_you":"Weekly budget sign-off."},{"n":"4","name":"Scale the organization","status":"GATED · NZ$40k MRR","routines":["Specialist agents","First human hire"],"from_you":"Hire and graduation decisions."}]'::jsonb, null
  where not exists (select 1 from plans where account_id = (select id from accounts where name = 'Unity MMA'));
insert into business_profiles (account_id, scan_status, profile, scanned_at)
  values ((select id from accounts where name = 'Unity MMA'), 'pending', '{"name":"Unity MMA","oneLiner":"Auckland MMA gym with credible coaches, an active member culture and technique content that already travels (one tutorial reached 45.8K views).","category":"MMA gym — memberships (Auckland)","products":["Memberships","Fundamentals classes","School programmes"],"audience":"Combat-sports followers worldwide for reach; Auckland locals for memberships","voice":{"tone":null,"phrases":[]},"market":{"region":"NZ","competitorsMentioned":[]},"signals":[],"confidence":"low","sources":["instagram.com/unitymma_"],"note":"Seeded by Junction from client files (scripts/seed-beta.ts) — no site scan has run.","beta":{"slug":"unity-mma","seeded_at":"2026-09-02T09:00:00.000Z","goal_source":"proposed","baseline_source":null,"baseline_as_of":null,"notes":["Source: projects/unity-mma-content-audit (Content & Growth Playbook, Aug 2026).","Known: Instagram @unitymma_; TikTok in scope (handle not recorded); coaches Brooke, Rory, Matt, Josh.","Unknown: owner''s name, website, membership numbers, current follower counts, ad spend, gym-management platform.","Goal line is a Junction proposal — confirm the number on the invite call. Baseline unknown (NULL).","No commerce/email/ads platform confirmed, so no connectors seeded."]}}'::jsonb, null)
  on conflict (account_id) do update set scan_status = excluded.scan_status, profile = excluded.profile, scanned_at = excluded.scanned_at, updated_at = now();
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'Unity MMA'), 'corner', 0, 'ai', 'unc', 'Kia ora there — Tom set this account up from what Junction already knows about Unity MMA, so you''re not starting from a blank page. Check the goal and the baseline on the Strategy view, then connect your platforms and I''ll start reading. Nothing publishes, sends or spends without your approval.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'Unity MMA'), 'human', 0, 'human', 'staff', 'Tom here — this is the human lane. Anything Unc gets wrong, or anything you''d rather say to a person, put it here.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into account_state_meta (account_id, schema_version, client_state, saved_at)
  values ((select id from accounts where name = 'Unity MMA'), 1, '{"onboarded":true,"obStep":6,"obCats":["leads"],"posture":"brand","goalTexts":{"revenue":"NZ$40,000 MRR","profit":"63% blended margin","brand":"25k engaged followers","leads":"30 new membership sign-ups/mo","retention":"22% repeat purchase rate","launch":"Launch the AU market"},"baselineText":"","targetNum":30,"obPace":"Steady · 4 weeks","profile":{"budget":"Not set yet","time":"Not set yet","strength":"Video & Community","belief":"Brand before sales","team":"Just me"},"routineEdits":{},"narrative":{"status":"idle","key":null,"baseKey":null,"value":null},"scanKey":null,"wfState":"clean","wfVer":12}'::jsonb, '2026-09-02T09:00:00.000Z'::timestamptz)
  on conflict (account_id) do update set schema_version = excluded.schema_version, client_state = excluded.client_state, saved_at = excluded.saved_at;
-- beta invite (fill the email, uncomment, apply — docs/BETA.md §Invite flow):
-- insert into beta_invites (account_id, email, role, invited_by, note)
--   select id, lower('[EMAIL: Unity MMA founder]'), 'owner', 'tom', 'unity-mma' from accounts where name = 'Unity MMA'
--   on conflict (email, account_id) do nothing;
-- ===== dbh → Deep Blue Health =====
insert into accounts (name, currency) select 'Deep Blue Health', 'NZD' where not exists (select 1 from accounts where name = 'Deep Blue Health');
update accounts set currency = 'NZD' where name = 'Deep Blue Health';
insert into goals (account_id, category, tier, title, baseline, baseline_date, deadline)
  values ((select id from accounts where name = 'Deep Blue Health'), 'retention', 'governing', '25% repeat purchase rate', null, null, '2027-03-01'::date)
  on conflict (account_id, category) do update set tier = excluded.tier, title = excluded.title, baseline = excluded.baseline, baseline_date = excluded.baseline_date, deadline = excluded.deadline, updated_at = now();
insert into resource_profiles (account_id, budget_monthly, hours_weekly, reinvestment, gross_margin_pct, website, socials, skills, known_platforms, postures, breadth)
  values ((select id from accounts where name = 'Deep Blue Health'), 0, 0, 'balanced', null, 'https://deepbluehealth.co.nz', '[]'::jsonb, array['Product', 'Email']::text[], array['Instagram', 'Facebook', 'Google (Search & Ads)', 'Email / SMS']::text[], array['brand_led', 'paid_led']::text[], 'broad')
  on conflict (account_id) do update set budget_monthly = excluded.budget_monthly, hours_weekly = excluded.hours_weekly, reinvestment = excluded.reinvestment, gross_margin_pct = excluded.gross_margin_pct, website = excluded.website, socials = excluded.socials, skills = excluded.skills, known_platforms = excluded.known_platforms, postures = excluded.postures, breadth = excluded.breadth, updated_at = now();
insert into team_members (account_id, position, name, role, approves)
  values ((select id from accounts where name = 'Deep Blue Health'), 0, 'You', 'Founder', 'Content, Paid ads, SEO, Sales, Email & SMS')
  on conflict (account_id, position) do update set name = excluded.name, role = excluded.role, approves = excluded.approves;
insert into plans (account_id, title, phases, narrative)
  select (select id from accounts where name = 'Deep Blue Health'), 'Brand-led organic', '[{"n":"1","name":"Organic brand engine","status":"ACTIVE","routines":["Founder content engine","Social repurposing","Customer-question mining"],"from_you":"~2 h/wk — your voice and taste, the part only you can do."},{"n":"2","name":"Retention & lifecycle","status":"NOW","routines":["Winback campaign prep","Welcome flow tuning","Review request timing"],"from_you":"~20 min/day clearing approvals."},{"n":"3","name":"Paid amplification","status":"GATED · repeat ≥ 18%","routines":["Daily paid decisioning","Organic-to-paid promotion"],"from_you":"Weekly budget sign-off."},{"n":"4","name":"Scale the organization","status":"GATED · NZ$40k MRR","routines":["Specialist agents","First human hire"],"from_you":"Hire and graduation decisions."}]'::jsonb, null
  where not exists (select 1 from plans where account_id = (select id from accounts where name = 'Deep Blue Health'));
insert into business_profiles (account_id, scan_status, profile, scanned_at)
  values ((select id from accounts where name = 'Deep Blue Health'), 'pending', '{"name":"Deep Blue Health","oneLiner":"New Zealand natural-health supplements (Green Lipped Mussel, colostrum, deer velvet, marine collagen and more) sold direct on Shopify.","category":"DTC supplements (NZ marine & natural health)","products":["Green Lipped Mussel","Colostrum","Deer Velvet","Marine Collagen","Propolis"],"audience":"Health-conscious buyers in NZ and export markets","voice":{"tone":null,"phrases":[]},"market":{"region":"NZ","competitorsMentioned":[]},"signals":[],"confidence":"low","sources":["https://deepbluehealth.co.nz"],"note":"Seeded by Junction from client files (scripts/seed-beta.ts) — no site scan has run.","beta":{"slug":"dbh","seeded_at":"2026-09-02T09:00:00.000Z","goal_source":"proposed","baseline_source":null,"baseline_as_of":null,"notes":["Source: clients/REGISTRY.md (DTC supplements, Managed Marketing); Junction''s own DBH work history (Shopify PDP engine, Klaviyo flows, Meta + Google Ads weeks).","Known: Shopify store; Klaviyo (two ''Placed Order'' metrics — the API one reads $0, use the warehouse); Meta Ads and Google Ads accounts in use.","Assumed: GA4 property exists (Google Ads in use) — confirm before it is offered as a connector.","Unknown this session: founder''s name (the client CLAUDE.md lives in ~/dbh-aios, unreadable on Drive today), Instagram handle (account dormant), revenue, repeat rate, ad budget.","Goal line is a Junction proposal (retention is DBH''s case-study focus) — confirm the number. Baseline unknown (NULL)."]}}'::jsonb, null)
  on conflict (account_id) do update set scan_status = excluded.scan_status, profile = excluded.profile, scanned_at = excluded.scanned_at, updated_at = now();
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'Deep Blue Health'), 'shopify', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'Deep Blue Health'), 'klaviyo', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'Deep Blue Health'), 'meta_ads', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'Deep Blue Health'), 'google_ads', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'Deep Blue Health'), 'ga4', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'Deep Blue Health'), 'corner', 0, 'ai', 'unc', 'Kia ora there — Tom set this account up from what Junction already knows about Deep Blue Health, so you''re not starting from a blank page. Check the goal and the baseline on the Strategy view, then connect Shopify, Klaviyo, Meta Ads, Google Ads, Google Analytics 4 and I''ll start reading. Nothing publishes, sends or spends without your approval.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'Deep Blue Health'), 'human', 0, 'human', 'staff', 'Tom here — this is the human lane. Anything Unc gets wrong, or anything you''d rather say to a person, put it here.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into account_state_meta (account_id, schema_version, client_state, saved_at)
  values ((select id from accounts where name = 'Deep Blue Health'), 1, '{"onboarded":true,"obStep":6,"obCats":["retention"],"posture":"brand","goalTexts":{"revenue":"NZ$40,000 MRR","profit":"63% blended margin","brand":"25k engaged followers","leads":"40 qualified leads/mo","retention":"25% repeat purchase rate","launch":"Launch the AU market"},"baselineText":"","targetNum":25,"obPace":"Steady · 4 weeks","profile":{"budget":"Not set yet","time":"Not set yet","strength":"Product & Email","belief":"Brand before sales + Buy learning fast","team":"Just me"},"routineEdits":{},"narrative":{"status":"idle","key":null,"baseKey":null,"value":null},"scanKey":null,"wfState":"clean","wfVer":12}'::jsonb, '2026-09-02T09:00:00.000Z'::timestamptz)
  on conflict (account_id) do update set schema_version = excluded.schema_version, client_state = excluded.client_state, saved_at = excluded.saved_at;
-- beta invite (fill the email, uncomment, apply — docs/BETA.md §Invite flow):
-- insert into beta_invites (account_id, email, role, invited_by, note)
--   select id, lower('[EMAIL: Deep Blue Health founder]'), 'owner', 'tom', 'dbh' from accounts where name = 'Deep Blue Health'
--   on conflict (email, account_id) do nothing;
-- ===== avgar → AVGAR Sport =====
insert into accounts (name, currency) select 'AVGAR Sport', 'NZD' where not exists (select 1 from accounts where name = 'AVGAR Sport');
update accounts set currency = 'NZD' where name = 'AVGAR Sport';
insert into goals (account_id, category, tier, title, baseline, baseline_date, deadline)
  values ((select id from accounts where name = 'AVGAR Sport'), 'revenue', 'governing', 'NZ$100,000 monthly revenue', 35000, '2026-07-12'::date, '2027-01-15'::date)
  on conflict (account_id, category) do update set tier = excluded.tier, title = excluded.title, baseline = excluded.baseline, baseline_date = excluded.baseline_date, deadline = excluded.deadline, updated_at = now();
insert into resource_profiles (account_id, budget_monthly, hours_weekly, reinvestment, gross_margin_pct, website, socials, skills, known_platforms, postures, breadth)
  values ((select id from accounts where name = 'AVGAR Sport'), 0, 0, 'balanced', null, 'https://avgarsport.com', '[]'::jsonb, array['Product', 'Design', 'Paid media']::text[], array['Instagram', 'Facebook', 'TikTok', 'Google (Search & Ads)', 'Email / SMS']::text[], array['brand_led', 'paid_led']::text[], 'broad')
  on conflict (account_id) do update set budget_monthly = excluded.budget_monthly, hours_weekly = excluded.hours_weekly, reinvestment = excluded.reinvestment, gross_margin_pct = excluded.gross_margin_pct, website = excluded.website, socials = excluded.socials, skills = excluded.skills, known_platforms = excluded.known_platforms, postures = excluded.postures, breadth = excluded.breadth, updated_at = now();
insert into team_members (account_id, position, name, role, approves)
  values ((select id from accounts where name = 'AVGAR Sport'), 0, 'Heather Anderson', 'Founder', 'Content, Paid ads, SEO, Sales, Email & SMS')
  on conflict (account_id, position) do update set name = excluded.name, role = excluded.role, approves = excluded.approves;
insert into team_members (account_id, position, name, role, approves)
  values ((select id from accounts where name = 'AVGAR Sport'), 1, 'Gwyn', 'Product', null)
  on conflict (account_id, position) do update set name = excluded.name, role = excluded.role, approves = excluded.approves;
insert into plans (account_id, title, phases, narrative)
  select (select id from accounts where name = 'AVGAR Sport'), 'Brand-led organic', '[{"n":"1","name":"Organic brand engine","status":"ACTIVE","routines":["Founder content engine","Social repurposing","Customer-question mining"],"from_you":"~2 h/wk — your voice and taste, the part only you can do."},{"n":"2","name":"Retention & lifecycle","status":"NOW","routines":["Winback campaign prep","Welcome flow tuning","Review request timing"],"from_you":"~20 min/day clearing approvals."},{"n":"3","name":"Paid amplification","status":"GATED · repeat ≥ 18%","routines":["Daily paid decisioning","Organic-to-paid promotion"],"from_you":"Weekly budget sign-off."},{"n":"4","name":"Scale the organization","status":"GATED · NZ$40k MRR","routines":["Specialist agents","First human hire"],"from_you":"Hire and graduation decisions."}]'::jsonb, null
  where not exists (select 1 from plans where account_id = (select id from accounts where name = 'AVGAR Sport'));
insert into business_profiles (account_id, scan_status, profile, scanned_at)
  values ((select id from accounts where name = 'AVGAR Sport'), 'pending', '{"name":"AVGAR Sport","oneLiner":"Luxury women''s golf brand (patent + FernMark + Certilogo behind the luxury claim), sold direct on Shopify.","category":"Luxury women''s golf apparel & accessories (DTC)","products":["Golf apparel","Golf bags","Accessories"],"audience":"Affluent women golfers — NZ proof base, Australia growth market","voice":{"tone":null,"phrases":[]},"market":{"region":"NZ / AU","competitorsMentioned":[]},"signals":[],"confidence":"low","sources":["https://avgarsport.com"],"note":"Seeded by Junction from client files (scripts/seed-beta.ts) — no site scan has run.","beta":{"slug":"avgar","seeded_at":"2026-09-02T09:00:00.000Z","goal_source":"client-docs","baseline_source":"Junction CLAUDE.md goal tracker — AVGAR 28-day revenue ~NZ$35K (▲69.7%) on 2026-07-12; target NZ$100–150K by 15 Jan 2027","baseline_as_of":"2026-07-12","notes":["Source: clients/avgar-sport/CHANNELS.md (8 in-scope channels; Shopify + GA4, Klaviyo, Meta Marketing API, Google Ads, Triple Whale) and the Junction root CLAUDE.md goal tracker.","Known: Heather Anderson (founder, taste gate) and Gwyn (product truth) are the two approvers; Fridays 16:00 NZT weekly report.","Baseline is the 28-day revenue reading from 2026-07-12 — refresh from avgar.v_* in the warehouse before it is shown as current.","Unknown: Instagram / TikTok handles (not recorded in the files read), ad budget, gross margin.","The NZ$10K/mo retainer is not an ad budget — budget left unknown."]}}'::jsonb, null)
  on conflict (account_id) do update set scan_status = excluded.scan_status, profile = excluded.profile, scanned_at = excluded.scanned_at, updated_at = now();
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'AVGAR Sport'), 'shopify', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'AVGAR Sport'), 'klaviyo', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'AVGAR Sport'), 'meta_ads', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'AVGAR Sport'), 'google_ads', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'AVGAR Sport'), 'ga4', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'AVGAR Sport'), 'corner', 0, 'ai', 'unc', 'Kia ora Heather — Tom set this account up from what Junction already knows about AVGAR Sport, so you''re not starting from a blank page. Check the goal and the baseline on the Strategy view, then connect Shopify, Klaviyo, Meta Ads, Google Ads, Google Analytics 4 and I''ll start reading. Nothing publishes, sends or spends without your approval.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'AVGAR Sport'), 'human', 0, 'human', 'staff', 'Tom here — this is the human lane. Anything Unc gets wrong, or anything you''d rather say to a person, put it here.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into account_state_meta (account_id, schema_version, client_state, saved_at)
  values ((select id from accounts where name = 'AVGAR Sport'), 1, '{"onboarded":true,"obStep":6,"obCats":["revenue"],"posture":"brand","goalTexts":{"revenue":"NZ$100,000 monthly revenue","profit":"63% blended margin","brand":"25k engaged followers","leads":"40 qualified leads/mo","retention":"22% repeat purchase rate","launch":"Launch the AU market"},"baselineText":"35,000 as of 2026-07-12","targetNum":100000,"obPace":"Steady · 4 weeks","profile":{"budget":"Not set yet","time":"Not set yet","strength":"Product & Design & Paid media","belief":"Brand before sales + Buy learning fast","team":"2 people"},"routineEdits":{},"narrative":{"status":"idle","key":null,"baseKey":null,"value":null},"scanKey":null,"wfState":"clean","wfVer":12}'::jsonb, '2026-09-02T09:00:00.000Z'::timestamptz)
  on conflict (account_id) do update set schema_version = excluded.schema_version, client_state = excluded.client_state, saved_at = excluded.saved_at;
-- beta invite (fill the email, uncomment, apply — docs/BETA.md §Invite flow):
-- insert into beta_invites (account_id, email, role, invited_by, note)
--   select id, lower('[EMAIL: Heather Anderson]'), 'owner', 'tom', 'avgar' from accounts where name = 'AVGAR Sport'
--   on conflict (email, account_id) do nothing;
-- ===== home-invasion → Home Invasion =====
insert into accounts (name, currency) select 'Home Invasion', 'USD' where not exists (select 1 from accounts where name = 'Home Invasion');
update accounts set currency = 'USD' where name = 'Home Invasion';
insert into goals (account_id, category, tier, title, baseline, baseline_date, deadline)
  values ((select id from accounts where name = 'Home Invasion'), 'revenue', 'governing', 'US$30,000 monthly revenue', null, null, '2027-03-01'::date)
  on conflict (account_id, category) do update set tier = excluded.tier, title = excluded.title, baseline = excluded.baseline, baseline_date = excluded.baseline_date, deadline = excluded.deadline, updated_at = now();
insert into resource_profiles (account_id, budget_monthly, hours_weekly, reinvestment, gross_margin_pct, website, socials, skills, known_platforms, postures, breadth)
  values ((select id from accounts where name = 'Home Invasion'), 0, 0, 'balanced', null, 'https://home1nvasion.com', '[]'::jsonb, array['Design', 'Product']::text[], array['Instagram', 'Facebook', 'Email / SMS']::text[], array['paid_led', 'brand_led']::text[], 'focused')
  on conflict (account_id) do update set budget_monthly = excluded.budget_monthly, hours_weekly = excluded.hours_weekly, reinvestment = excluded.reinvestment, gross_margin_pct = excluded.gross_margin_pct, website = excluded.website, socials = excluded.socials, skills = excluded.skills, known_platforms = excluded.known_platforms, postures = excluded.postures, breadth = excluded.breadth, updated_at = now();
insert into team_members (account_id, position, name, role, approves)
  values ((select id from accounts where name = 'Home Invasion'), 0, 'Zac', 'Founder', 'Content, Paid ads, SEO, Sales, Email & SMS')
  on conflict (account_id, position) do update set name = excluded.name, role = excluded.role, approves = excluded.approves;
insert into plans (account_id, title, phases, narrative)
  select (select id from accounts where name = 'Home Invasion'), 'Paid-led scale', '[{"n":"1","name":"Creative testing engine","status":"WOULD ACTIVATE","routines":["Creative test planner","Organic-to-paid promotion"],"from_you":"Creative taste calls, weekly."},{"n":"2","name":"Spend scaling","status":"GATED · ROAS ≥ 2.5×","routines":["Daily paid decisioning","Budget pacing guard"],"from_you":"Budget sign-off as caps rise."},{"n":"3","name":"Funnel & flows","status":"NEXT","routines":["Welcome flow tuning","Abandoned cart recovery"],"from_you":"Approve test variants."},{"n":"4","name":"Scale the organization","status":"GATED · NZ$40k MRR","routines":["Specialist agents","Media buyer hire"],"from_you":"Hire and graduation decisions."}]'::jsonb, null
  where not exists (select 1 from plans where account_id = (select id from accounts where name = 'Home Invasion'));
insert into business_profiles (account_id, scan_status, profile, scanned_at)
  values ((select id from accounts where name = 'Home Invasion'), 'pending', '{"name":"Home Invasion","oneLiner":"Hip-hop and pop-culture home decor — rugs and plushies — sold direct on Shopify; Meta ads are the primary lane.","category":"DTC hip-hop / pop-culture home decor (rugs, plushies)","products":["Rugs","Plushies"],"audience":"Hip-hop / streetwear culture buyers","voice":{"tone":null,"phrases":[]},"market":{"region":"Auckland-based, trades in USD and ships worldwide (store meta: country NZ, currency USD)","competitorsMentioned":[]},"signals":[],"confidence":"low","sources":["https://home1nvasion.com"],"note":"Seeded by Junction from client files (scripts/seed-beta.ts) — no site scan has run.","beta":{"slug":"home-invasion","seeded_at":"2026-09-02T09:00:00.000Z","goal_source":"proposed","baseline_source":null,"baseline_as_of":null,"notes":["Source: clients/home-invasion/CHANNELS.md (Shopify, Klaviyo installed, Meta pixel installed, IG handle TBC; in scope: Meta ads primary, email, organic, SEO) and clients/REGISTRY.md.","Known: founder Zac; install started 2026-08-06 on the founder''s Claude Max.","Unknown: Instagram handle (TBC in the client file), GA4 property (TBC — not seeded), revenue, budget, margin.","Currency USD — verified 2026-09-02 from the live store (www.home1nvasion.com/meta.json: currency USD, country NZ, myshopify domain home1nvasionstore.myshopify.com; products.json prices e.g. 160.00). Business is Auckland-based.","Goal line is a Junction placeholder — confirm the number. Baseline unknown (NULL)."]}}'::jsonb, null)
  on conflict (account_id) do update set scan_status = excluded.scan_status, profile = excluded.profile, scanned_at = excluded.scanned_at, updated_at = now();
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'Home Invasion'), 'shopify', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'Home Invasion'), 'klaviyo', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into connectors (account_id, platform, status)
  values ((select id from accounts where name = 'Home Invasion'), 'meta_ads', 'disconnected')
  on conflict (account_id, platform) do nothing;
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'Home Invasion'), 'corner', 0, 'ai', 'unc', 'Kia ora Zac — Tom set this account up from what Junction already knows about Home Invasion, so you''re not starting from a blank page. Check the goal and the baseline on the Strategy view, then connect Shopify, Klaviyo, Meta Ads and I''ll start reading. Nothing publishes, sends or spends without your approval.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'Home Invasion'), 'human', 0, 'human', 'staff', 'Tom here — this is the human lane. Anything Unc gets wrong, or anything you''d rather say to a person, put it here.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into account_state_meta (account_id, schema_version, client_state, saved_at)
  values ((select id from accounts where name = 'Home Invasion'), 1, '{"onboarded":true,"obStep":6,"obCats":["revenue"],"posture":"paid","goalTexts":{"revenue":"US$30,000 monthly revenue","profit":"63% blended margin","brand":"25k engaged followers","leads":"40 qualified leads/mo","retention":"22% repeat purchase rate","launch":"Launch the AU market"},"baselineText":"","targetNum":30000,"obPace":"Steady · 4 weeks","profile":{"budget":"Not set yet","time":"Not set yet","strength":"Design & Product","belief":"Buy learning fast + Brand before sales","team":"Just me"},"routineEdits":{},"narrative":{"status":"idle","key":null,"baseKey":null,"value":null},"scanKey":null,"wfState":"clean","wfVer":12}'::jsonb, '2026-09-02T09:00:00.000Z'::timestamptz)
  on conflict (account_id) do update set schema_version = excluded.schema_version, client_state = excluded.client_state, saved_at = excluded.saved_at;
-- beta invite (fill the email, uncomment, apply — docs/BETA.md §Invite flow):
-- insert into beta_invites (account_id, email, role, invited_by, note)
--   select id, lower('[EMAIL: Zac]'), 'owner', 'tom', 'home-invasion' from accounts where name = 'Home Invasion'
--   on conflict (email, account_id) do nothing;
-- ===== rory → Rory O'Keefe =====
insert into accounts (name, currency) select 'Rory O''Keefe', 'NZD' where not exists (select 1 from accounts where name = 'Rory O''Keefe');
update accounts set currency = 'NZD' where name = 'Rory O''Keefe';
insert into goals (account_id, category, tier, title, baseline, baseline_date, deadline)
  values ((select id from accounts where name = 'Rory O''Keefe'), 'brand', 'governing', '100,000 engaged followers', null, null, '2026-12-31'::date)
  on conflict (account_id, category) do update set tier = excluded.tier, title = excluded.title, baseline = excluded.baseline, baseline_date = excluded.baseline_date, deadline = excluded.deadline, updated_at = now();
insert into resource_profiles (account_id, budget_monthly, hours_weekly, reinvestment, gross_margin_pct, website, socials, skills, known_platforms, postures, breadth)
  values ((select id from accounts where name = 'Rory O''Keefe'), 0, 0, 'balanced', null, null, '[]'::jsonb, array['Video', 'Product', 'Design']::text[], array['Instagram']::text[], array['brand_led', 'sales_led']::text[], 'focused')
  on conflict (account_id) do update set budget_monthly = excluded.budget_monthly, hours_weekly = excluded.hours_weekly, reinvestment = excluded.reinvestment, gross_margin_pct = excluded.gross_margin_pct, website = excluded.website, socials = excluded.socials, skills = excluded.skills, known_platforms = excluded.known_platforms, postures = excluded.postures, breadth = excluded.breadth, updated_at = now();
insert into team_members (account_id, position, name, role, approves)
  values ((select id from accounts where name = 'Rory O''Keefe'), 0, 'Rory O''Keefe', 'Founder', 'Content, Paid ads, SEO, Sales, Email & SMS')
  on conflict (account_id, position) do update set name = excluded.name, role = excluded.role, approves = excluded.approves;
insert into plans (account_id, title, phases, narrative)
  select (select id from accounts where name = 'Rory O''Keefe'), 'Brand-led organic', '[{"n":"1","name":"Organic brand engine","status":"ACTIVE","routines":["Founder content engine","Social repurposing","Customer-question mining"],"from_you":"~2 h/wk — your voice and taste, the part only you can do."},{"n":"2","name":"Retention & lifecycle","status":"NOW","routines":["Winback campaign prep","Welcome flow tuning","Review request timing"],"from_you":"~20 min/day clearing approvals."},{"n":"3","name":"Paid amplification","status":"GATED · repeat ≥ 18%","routines":["Daily paid decisioning","Organic-to-paid promotion"],"from_you":"Weekly budget sign-off."},{"n":"4","name":"Scale the organization","status":"GATED · NZ$40k MRR","routines":["Specialist agents","First human hire"],"from_you":"Hire and graduation decisions."}]'::jsonb, null
  where not exists (select 1 from plans where account_id = (select id from accounts where name = 'Rory O''Keefe'));
insert into business_profiles (account_id, scan_status, profile, scanned_at)
  values ((select id from accounts where name = 'Rory O''Keefe'), 'pending', '{"name":"Rory O''Keefe","oneLiner":"Product design services, grown through an Instagram-led founder brand (The Corner daily coaching + weekly leaderboard).","category":"Product design services (consultancy)","products":["Product design services"],"audience":"Founders and brands needing product design; Instagram audience for reach","voice":{"tone":null,"phrases":[]},"market":{"region":"NZ","competitorsMentioned":[]},"signals":[],"confidence":"low","sources":[],"note":"Seeded by Junction from client files (scripts/seed-beta.ts) — no site scan has run.","beta":{"slug":"rory","seeded_at":"2026-09-02T09:00:00.000Z","goal_source":"client-docs","baseline_source":null,"baseline_as_of":null,"notes":["Source: clients/REGISTRY.md (Product design services, Active — AI OS); Junction''s The Corner / Rory Corner console-agent work (goals 20K followers Jul 2026 / 100K Dec 2026).","Unknown this session: website, Instagram handle (clients/rory-okeefe/CLIENT-BRIEF.md and THE-PLAN-2026-08-04.md timed out on Drive), current follower count, revenue.","Baseline unknown (NULL) — the rory.v_* views hold the follower series; pull the latest before the invite.","No commerce/email/ads connector known — none seeded."]}}'::jsonb, null)
  on conflict (account_id) do update set scan_status = excluded.scan_status, profile = excluded.profile, scanned_at = excluded.scanned_at, updated_at = now();
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'Rory O''Keefe'), 'corner', 0, 'ai', 'unc', 'Kia ora Rory — Tom set this account up from what Junction already knows about Rory O''Keefe, so you''re not starting from a blank page. Check the goal and the baseline on the Strategy view, then connect your platforms and I''ll start reading. Nothing publishes, sends or spends without your approval.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'Rory O''Keefe'), 'human', 0, 'human', 'staff', 'Tom here — this is the human lane. Anything Unc gets wrong, or anything you''d rather say to a person, put it here.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into account_state_meta (account_id, schema_version, client_state, saved_at)
  values ((select id from accounts where name = 'Rory O''Keefe'), 1, '{"onboarded":true,"obStep":6,"obCats":["brand"],"posture":"brand","goalTexts":{"revenue":"NZ$40,000 MRR","profit":"63% blended margin","brand":"100,000 engaged followers","leads":"40 qualified leads/mo","retention":"22% repeat purchase rate","launch":"Launch the AU market"},"baselineText":"","targetNum":100000,"obPace":"Steady · 4 weeks","profile":{"budget":"Not set yet","time":"Not set yet","strength":"Video & Product & Design","belief":"Brand before sales + Sales conversations first","team":"Just me"},"routineEdits":{},"narrative":{"status":"idle","key":null,"baseKey":null,"value":null},"scanKey":null,"wfState":"clean","wfVer":12}'::jsonb, '2026-09-02T09:00:00.000Z'::timestamptz)
  on conflict (account_id) do update set schema_version = excluded.schema_version, client_state = excluded.client_state, saved_at = excluded.saved_at;
-- beta invite (fill the email, uncomment, apply — docs/BETA.md §Invite flow):
-- insert into beta_invites (account_id, email, role, invited_by, note)
--   select id, lower('[EMAIL: Rory O'Keefe]'), 'owner', 'tom', 'rory' from accounts where name = 'Rory O''Keefe'
--   on conflict (email, account_id) do nothing;
-- ===== aerspan → Aerspan Airdomes =====
insert into accounts (name, currency) select 'Aerspan Airdomes', 'NZD' where not exists (select 1 from accounts where name = 'Aerspan Airdomes');
update accounts set currency = 'NZD' where name = 'Aerspan Airdomes';
insert into goals (account_id, category, tier, title, baseline, baseline_date, deadline)
  values ((select id from accounts where name = 'Aerspan Airdomes'), 'leads', 'governing', '12 signed dome projects per year', 0, '2026-08-12'::date, '2027-03-01'::date)
  on conflict (account_id, category) do update set tier = excluded.tier, title = excluded.title, baseline = excluded.baseline, baseline_date = excluded.baseline_date, deadline = excluded.deadline, updated_at = now();
insert into resource_profiles (account_id, budget_monthly, hours_weekly, reinvestment, gross_margin_pct, website, socials, skills, known_platforms, postures, breadth)
  values ((select id from accounts where name = 'Aerspan Airdomes'), 0, 0, 'balanced', null, 'https://aerspanairdomes.com', '[]'::jsonb, array['Sales conversations', 'Email']::text[], array['LinkedIn', 'Email / SMS']::text[], array['sales_led']::text[], 'focused')
  on conflict (account_id) do update set budget_monthly = excluded.budget_monthly, hours_weekly = excluded.hours_weekly, reinvestment = excluded.reinvestment, gross_margin_pct = excluded.gross_margin_pct, website = excluded.website, socials = excluded.socials, skills = excluded.skills, known_platforms = excluded.known_platforms, postures = excluded.postures, breadth = excluded.breadth, updated_at = now();
insert into team_members (account_id, position, name, role, approves)
  values ((select id from accounts where name = 'Aerspan Airdomes'), 0, 'Mike Hall-Taylor', 'Founder', 'Content, Paid ads, SEO, Sales, Email & SMS')
  on conflict (account_id, position) do update set name = excluded.name, role = excluded.role, approves = excluded.approves;
insert into team_members (account_id, position, name, role, approves)
  values ((select id from accounts where name = 'Aerspan Airdomes'), 1, 'Brett', 'Sales', null)
  on conflict (account_id, position) do update set name = excluded.name, role = excluded.role, approves = excluded.approves;
insert into team_members (account_id, position, name, role, approves)
  values ((select id from accounts where name = 'Aerspan Airdomes'), 2, 'Daniel Clapham', 'Sales', null)
  on conflict (account_id, position) do update set name = excluded.name, role = excluded.role, approves = excluded.approves;
insert into plans (account_id, title, phases, narrative)
  select (select id from accounts where name = 'Aerspan Airdomes'), 'Sales-led outbound', '[{"n":"1","name":"Pipeline engine","status":"WOULD ACTIVATE","routines":["Lead research & scoring","Supervised outbound drafts"],"from_you":"~1 h/day — conversations and closing, your strength."},{"n":"2","name":"Follow-up & pipeline","status":"NEXT","routines":["Follow-up cadence","Pipeline hygiene"],"from_you":"Approve sends; take the meetings."},{"n":"3","name":"Referral & expansion","status":"GATED · 20 closed deals","routines":["Review request timing","Winback campaign prep"],"from_you":"The asks only a founder can make."},{"n":"4","name":"Scale the organization","status":"GATED · NZ$40k MRR","routines":["Sales agents","First SDR hire"],"from_you":"Hire and graduation decisions."}]'::jsonb, null
  where not exists (select 1 from plans where account_id = (select id from accounts where name = 'Aerspan Airdomes'));
insert into business_profiles (account_id, scan_status, profile, scanned_at)
  values ((select id from accounts where name = 'Aerspan Airdomes'), 'pending', '{"name":"Aerspan Airdomes","oneLiner":"Exclusive NZ/Australia/Oceania distributor for DUOL air-supported domes — indoor sports and community facilities, sold against bricks-and-mortar builds.","category":"B2B air-supported dome buildings (sports & community facilities)","products":["Air-supported dome facilities (DUOL)"],"audience":"Clubs, schools, councils and sports trusts that already want an indoor facility and hold ~$10m construction quotes","voice":{"tone":null,"phrases":[]},"market":{"region":"NZ first (Auckland), then Australia","competitorsMentioned":[]},"signals":[],"confidence":"low","sources":["https://aerspanairdomes.com"],"note":"Seeded by Junction from client files (scripts/seed-beta.ts) — no site scan has run.","beta":{"slug":"aerspan","seeded_at":"2026-09-02T09:00:00.000Z","goal_source":"client-docs","baseline_source":"clients/aerspan-airdomes/CLAUDE.md — company incorporated 2026, no completed NZ project yet; Counties Tennis at tender/contract stage, not signed","baseline_as_of":"2026-08-12","notes":["Source: clients/aerspan-airdomes/CLAUDE.md (goal: 12 projects a year, one a month, NZ then AU; team Brett + Daniel Clapham; supplier DUOL; long-cycle named-prospect outreach, draft-only, Mike sends).","Website is the company mailbox domain (aerspanairdomes.com, Microsoft 365) — site existence not verified. Mike''s address is not stored here — it is entered on the invite row at invite time.","Baseline 0 is a FOUND fact (no signed/completed NZ project as of 2026-08-12), not a null written as 0.","Deadline is the 6-month horizon; the goal itself is annual (12/yr ≈ 6 signed in the window).","Claims law applies: DUOL''s record ≠ Aerspan''s; the price wedge is banned from cold email.","No Shopify/Klaviyo/ads; email is Microsoft 365 (GoDaddy-provisioned, federated) — no connector in the registry for it yet."]}}'::jsonb, null)
  on conflict (account_id) do update set scan_status = excluded.scan_status, profile = excluded.profile, scanned_at = excluded.scanned_at, updated_at = now();
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'Aerspan Airdomes'), 'corner', 0, 'ai', 'unc', 'Kia ora Mike — Tom set this account up from what Junction already knows about Aerspan Airdomes, so you''re not starting from a blank page. Check the goal and the baseline on the Strategy view, then connect your platforms and I''ll start reading. Nothing publishes, sends or spends without your approval.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into chat_messages (account_id, thread, position, lane, sender, body, meta)
  values ((select id from accounts where name = 'Aerspan Airdomes'), 'human', 0, 'human', 'staff', 'Tom here — this is the human lane. Anything Unc gets wrong, or anything you''d rather say to a person, put it here.', '{}'::jsonb)
  on conflict (account_id, thread, position) do nothing;
insert into account_state_meta (account_id, schema_version, client_state, saved_at)
  values ((select id from accounts where name = 'Aerspan Airdomes'), 1, '{"onboarded":true,"obStep":6,"obCats":["leads"],"posture":"sales","goalTexts":{"revenue":"NZ$40,000 MRR","profit":"63% blended margin","brand":"25k engaged followers","leads":"12 signed dome projects per year","retention":"22% repeat purchase rate","launch":"Launch the AU market"},"baselineText":"0 as of 2026-08-12","targetNum":12,"obPace":"Steady · 4 weeks","profile":{"budget":"Not set yet","time":"Not set yet","strength":"Sales conversations & Email","belief":"Sales conversations first","team":"3 people"},"routineEdits":{},"narrative":{"status":"idle","key":null,"baseKey":null,"value":null},"scanKey":null,"wfState":"clean","wfVer":12}'::jsonb, '2026-09-02T09:00:00.000Z'::timestamptz)
  on conflict (account_id) do update set schema_version = excluded.schema_version, client_state = excluded.client_state, saved_at = excluded.saved_at;
-- beta invite (fill the email, uncomment, apply — docs/BETA.md §Invite flow):
-- insert into beta_invites (account_id, email, role, invited_by, note)
--   select id, lower('[EMAIL: Mike Hall-Taylor]'), 'owner', 'tom', 'aerspan' from accounts where name = 'Aerspan Airdomes'
--   on conflict (email, account_id) do nothing;
