-- Applied as 20260908154544. Action approval is not execution.
create table public.review_action_approvals (
 id uuid primary key,
 account_id uuid not null,
 output_id uuid not null,
 output_revision bigint not null,
 action text not null check(action in ('prepare_provider_draft','send','publish','change_ads')),
 target_id text not null check(length(btrim(target_id)) between 1 and 200),
 description text not null check(length(btrim(description)) between 1 and 4000),
 action_payload jsonb not null check(jsonb_typeof(action_payload)='object' and octet_length(action_payload::text)<=200000),
 expires_at timestamptz not null,
 status text not null default 'pending' check(status in ('pending','approved','held')),
 decided_by uuid,
 decided_at timestamptz,
 created_at timestamptz not null default now(),
 foreign key(output_id,account_id) references public.review_outputs(id,account_id),
 foreign key(output_id,output_revision) references public.review_output_versions(output_id,revision),
 check((status='pending' and decided_by is null and decided_at is null) or
       (status<>'pending' and decided_by is not null and decided_at is not null))
);
create index review_action_approvals_output on public.review_action_approvals(account_id,output_id,created_at);
alter table public.review_action_approvals enable row level security;
revoke all on public.review_action_approvals from public,anon,authenticated;
grant select,insert on public.review_action_approvals to service_role;
grant update(status,decided_by,decided_at) on public.review_action_approvals to service_role;

-- Trusted producer supplies the exact connector action payload; never generated by the browser.
create function public.propose_review_action(acct uuid,generation bigint,output uuid,expected_revision bigint,
 proposal uuid,action_value text,target_value text,description_value text,payload jsonb,expiry timestamptz)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare o public.review_outputs%rowtype; old public.review_action_approvals%rowtype;
begin
 perform 1 from public.accounts where id=acct and context_generation=generation for share;
 if not found then raise exception 'Context changed' using errcode='40001'; end if;
 select ro.* into o from public.review_outputs ro
 join public.artifacts a on a.id=ro.artifact_id and a.account_id=ro.account_id
 join public.routine_runs r on r.id=a.run_id and r.account_id=a.account_id
 where ro.id=output and ro.account_id=acct and ro.context_generation=generation and r.context_generation=generation for update of ro;
 if not found then raise exception 'Output unavailable' using errcode='42501'; end if;
 if expected_revision is distinct from o.revision then raise exception 'Output changed' using errcode='40001'; end if;
 if proposal is null or expiry is null or expiry<=now() or expiry>now()+interval '7 days' then
   raise exception 'Invalid proposal expiry' using errcode='22023'; end if;
 perform pg_advisory_xact_lock(hashtextextended('review-action:'||proposal::text,0));
 select * into old from public.review_action_approvals where id=proposal;
 if found then
  if old.account_id is distinct from acct or old.output_id is distinct from output or old.output_revision is distinct from expected_revision
   or old.action is distinct from action_value or old.target_id is distinct from target_value
   or old.description is distinct from description_value or old.action_payload is distinct from payload or old.expires_at is distinct from expiry
   then raise exception 'Proposal ID conflict' using errcode='40001'; end if;
  return jsonb_build_object('proposalId',proposal,'duplicate',true);
 end if;
 insert into public.review_action_approvals(id,account_id,output_id,output_revision,action,target_id,description,action_payload,expires_at)
 values(proposal,acct,output,expected_revision,action_value,target_value,description_value,payload,expiry);
 return jsonb_build_object('proposalId',proposal,'duplicate',false);
end $$;
revoke all on function public.propose_review_action(uuid,bigint,uuid,bigint,uuid,text,text,text,jsonb,timestamptz) from public,anon,authenticated;
grant execute on function public.propose_review_action(uuid,bigint,uuid,bigint,uuid,text,text,text,jsonb,timestamptz) to service_role;

create function public.read_review_actions(acct uuid,generation bigint,actor uuid,output uuid)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare current_review jsonb; actions jsonb; can_decide boolean;
begin
 current_review:=public.read_review_output(acct,generation,actor,output);
 if current_review is null then return null; end if;
 select role='owner' into can_decide from public.account_members where account_id=acct and user_id=actor;
 select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'revision',p.output_revision,'action',p.action,
   'targetId',p.target_id,'description',p.description,'expiresAt',p.expires_at,'status',p.status,
   'effectiveStatus',case when p.output_revision<>(current_review->'output'->>'revision')::bigint then 'superseded'
     when p.expires_at<=now() then 'expired' else p.status end) order by p.created_at desc,p.id),'[]'::jsonb)
 into actions from (select * from public.review_action_approvals where account_id=acct and output_id=output order by created_at desc,id limit 50) p;
 return jsonb_build_object('output',current_review->'output','canDecide',can_decide,'actions',actions);
end $$;
revoke all on function public.read_review_actions(uuid,bigint,uuid,uuid) from public,anon,authenticated;
grant execute on function public.read_review_actions(uuid,bigint,uuid,uuid) to service_role;

create function public.decide_review_action(acct uuid,generation bigint,actor uuid,output uuid,expected_revision bigint,proposal uuid,decision text)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare o public.review_outputs%rowtype; p public.review_action_approvals%rowtype;
begin
 perform 1 from public.accounts where id=acct and context_generation=generation for share;
 if not found then raise exception 'Context changed' using errcode='40001'; end if;
 perform 1 from public.account_members where account_id=acct and user_id=actor and role='owner' for share;
 if not found then raise exception 'Owner required' using errcode='42501'; end if;
 select ro.* into o from public.review_outputs ro
 join public.artifacts a on a.id=ro.artifact_id and a.account_id=ro.account_id
 join public.routine_runs r on r.id=a.run_id and r.account_id=a.account_id
 where ro.id=output and ro.account_id=acct and ro.context_generation=generation and r.context_generation=generation for update of ro;
 if not found then raise exception 'Output unavailable' using errcode='42501'; end if;
 select * into p from public.review_action_approvals where id=proposal and account_id=acct and output_id=output for update;
 if not found then raise exception 'Proposal unavailable' using errcode='42501'; end if;
 if expected_revision is distinct from o.revision or p.output_revision<>o.revision or p.expires_at<=now() then
   raise exception 'Proposal changed or expired' using errcode='40001'; end if;
 if decision is null or decision not in ('approved','held') then raise exception 'Invalid decision' using errcode='22023'; end if;
 if p.status=decision and p.decided_by=actor then
   return jsonb_build_object('proposalId',proposal,'revision',p.output_revision,'status',decision,'duplicate',true,'executed',false); end if;
 -- A hold can revoke approval before any executor has been introduced. Held is terminal.
 if p.status<>'pending' and not(p.status='approved' and decision='held') then
   raise exception 'Already decided' using errcode='40001'; end if;
 update public.review_action_approvals set status=decision,decided_by=actor,decided_at=now() where id=proposal;
 return jsonb_build_object('proposalId',proposal,'revision',p.output_revision,'status',decision,'duplicate',false,'executed',false);
end $$;
revoke all on function public.decide_review_action(uuid,bigint,uuid,uuid,bigint,uuid,text) from public,anon,authenticated;
grant execute on function public.decide_review_action(uuid,bigint,uuid,uuid,bigint,uuid,text) to service_role;
